# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Tests

on:
  workflow_dispatch:
    inputs:
      tests-to-run:
        description: 'Tests to Execute (ex. Hype Machine). To run all tests enter  "."'
        # Specify if you only want to run specific tests. 
        default: '.'
        # Input has to be provided for the workflow to run
        required: true
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --grep "${{ github.event.inputs.tests-to-run }}"
